[CmdletBinding()] param()
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; $root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
& (Join-Path $root 'scripts/verify.ps1') | Out-Null
$manifest=Get-Content -Raw (Join-Path $root 'portable-manifest.json')|ConvertFrom-Json
if(@($manifest.skills).Count -ne 3 -or @($manifest.skills|Where-Object{$_ -notin @('sdd-workflow','systematic-debugging','repo-aware-architecture')}).Count -ne 0){throw 'Skill allowlist mismatch'}
$run=Get-Content -Raw (Join-Path $root 'bin/agentic-run.ps1'); if($run -match '(?i)while\s*\('){throw 'Runner polling loop found'}; if($run -notmatch 'wait-policy.json'){throw 'Runner wait policy missing'}; if($run -notmatch 'RuntimeRoot must be outside'){throw 'Runtime safety missing'}
$exec=Get-Content -Raw (Join-Path $root 'bin/agentic-execute.ps1'); if($exec -match '\[ValidateSet|WorkflowPath|\$Action|\$RunId|\$RuntimeRoot'){throw 'Legacy execute semantics remain'}; if($exec -notmatch 'constraints-overlay'){throw 'Overlay contract missing'}
$final=Get-Content -Raw (Join-Path $root 'bin/agentic-finalize.ps1'); if($final -match 'workflow-receipts|Import-Csv|Export-Csv'){throw 'Finalizer legacy dependency/CSV path found'}; if($final -notmatch 'allowExternal|allowedRoots'){throw 'Round log safety missing'}
$runtime=Get-Content -Raw (Join-Path $root 'adapters/codex/runtime.md'); if($runtime -notmatch 'host/user selects the root|Sol.*decision-only|fork_turns'){throw 'Codex runtime policy incomplete'}
$global=Get-Content -Raw (Join-Path $root 'global/AGENTS.md'); if($global.Length -gt 15000 -or $global -notmatch 'index first|replacement'){throw 'Global policy budget/contract failed'}
$request=Join-Path ([IO.Path]::GetTempPath()) 'v4-kernel-test.json'; [IO.File]::WriteAllText($request,'{"schemaVersion":1,"kind":"kernel-request","role":"implementer","workerId":"worker-1","constraintsOverlay":true,"contextSources":["README.md"],"budgets":{"contextTokens":512,"outputTokens":128}}'); $out=& (Join-Path $root 'bin/agentic-kernel.ps1') -RequestPath $request|ConvertFrom-Json; if($out.root -ne 'host-selected' -or $out.status -ne 'READY'){throw 'Kernel root contract failed'}
$replacement=Join-Path ([IO.Path]::GetTempPath()) 'v4-kernel-replacement.json'; [IO.File]::WriteAllText($replacement,'{"schemaVersion":1,"kind":"kernel-request","role":"implementer","failure":{"workerId":"worker-1","reason":"usage-limit"},"contextSources":["README.md"],"budgets":{"contextTokens":512,"outputTokens":128}}'); $r=& (Join-Path $root 'bin/agentic-kernel.ps1') -RequestPath $replacement|ConvertFrom-Json; if($r.status -ne 'REPLACEMENT_REQUIRED' -or $r.replacement.workerId -ne 'worker-1-replacement'){throw 'Replacement contract failed'}
$source=Join-Path ([IO.Path]::GetTempPath()) 'execute-source.md'; [IO.File]::WriteAllText($source,'constraints'); $o=& (Join-Path $root 'bin/agentic-execute.ps1') -ProjectRoot ([IO.Path]::GetTempPath()) -SourcePath 'execute-source.md' -AsJson|ConvertFrom-Json; if($o.kind -ne 'constraints-overlay' -or $o.root -ne 'host-selected'){throw 'Execute overlay failed'}
Write-Host 'V4 hardening tests passed.'
