[CmdletBinding()] param()
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
& (Join-Path $root 'scripts/verify.ps1') | Out-Null
function Require([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function ExpectFailure([scriptblock]$Action,[string]$Message){$failed=$false;try{& $Action}catch{$failed=$true};Require $failed $Message}
$manifest=Get-Content -Raw (Join-Path $root 'portable-manifest.json')|ConvertFrom-Json
Require (@($manifest.skills).Count -eq 3) 'Skill count mismatch'
foreach($skill in @('sdd-workflow','systematic-debugging','repo-aware-architecture')){Require ($manifest.skills -contains $skill) "Missing skill: $skill"}
$sdd=Get-Content -Raw (Join-Path $root 'skills/sdd-workflow/SKILL.md'); Require ($sdd -notmatch '(?i)select the root model|Sol executes directly|model-routing') 'SDD contains legacy routing'; Require (-not (Test-Path (Join-Path $root 'skills/sdd-workflow/references/model-routing.md'))) 'Legacy routing file remains'
$runtime=Get-Content -Raw (Join-Path $root 'adapters/codex/runtime.md'); $runtimeFlat=($runtime -replace '\s+',' ').Trim()
foreach($needle in @('host/user selects the root','Luna Medium is','Sol is architect_escalation only','first escalation is Sol Low','fork_turns none','three concurrent workers','equivalent replacement worker','root does not inherit','Root takeover is permitted only','same implementer')){Require ($runtimeFlat.Contains($needle)) "Runtime invariant missing: $needle"}
$global=Get-Content -Raw (Join-Path $root 'global/AGENTS.md'); Require ($global.Length -le 6144) "Global AGENTS exceeds 6KB: $($global.Length)"
$profile=Get-Content -Raw (Join-Path $root 'profiles/coder/PROFILE.md'); Require ($profile.Contains('correction ownership returns to the existing implementer or writer')) 'Reviewer-to-writer policy missing'
Require ($profile.Contains('same implementer or writer') -or $runtime.Contains('same implementer')) 'Reviewer finding does not return to writer'; Require ($runtimeFlat.Contains('Ordinary tasks use the base harness')) 'Ordinary task harness contract missing'; Require ($runtimeFlat.Contains('/execute adds declared constraints')) 'Execute overlay contract missing'
Require ((Get-Item (Join-Path $root 'adapters/codex/runtime.md')).Length -le 4096) 'Codex runtime size budget exceeded'; Require ((Get-Item (Join-Path $root 'profiles/coder/PROFILE.md')).Length -le 6144) 'Coder profile size budget exceeded'; Require ((Get-Item (Join-Path $root 'skills/sdd-workflow/SKILL.md')).Length -le 4096) 'SDD skill size budget exceeded'; $refFiles=if(Test-Path (Join-Path $root 'skills/sdd-workflow/references')){@(Get-ChildItem (Join-Path $root 'skills/sdd-workflow/references') -File)}else{@()}; $refBytes=[int64](($refFiles | ForEach-Object {[int64]$_.Length} | Measure-Object -Sum).Sum); if($null -eq $refBytes){$refBytes=0}; Require ($refBytes -eq 0) "Legacy SDD references remain: $refBytes bytes"
$run=Get-Content -Raw (Join-Path $root 'bin/agentic-run.ps1'); Require ($run -notmatch '(?i)while\s*\(') 'Runner polling loop found'; Require ($run.Contains('wait-policy.json')) 'Runner wait policy missing'; Require ($run.Contains('RuntimeRoot must be outside')) 'Runtime safety missing'
$final=Get-Content -Raw (Join-Path $root 'bin/agentic-finalize.ps1'); foreach($needle in @('allowExternal','allowedRoots','GateReceiptPath','AllowCommit','AppendAllText')){Require ($final.Contains($needle)) "Finalizer contract missing: $needle"}; Require ($final -notmatch 'workflow-receipts|Import-Csv|Export-Csv') 'Finalizer legacy dependency found'
$exec=Get-Content -Raw (Join-Path $root 'bin/agentic-execute.ps1'); Require ($exec.Contains('constraints-overlay')) 'Overlay contract missing'; Require ($exec.Contains('SourcePath escapes ProjectRoot')) 'Execute path guard missing'
$policy=Get-Content -Raw (Join-Path $root 'config/wait-policy.json')|ConvertFrom-Json; Require ($policy.defaultCommandTimeoutSeconds -eq 3600 -and $policy.defaultAgentWaitSeconds -eq 3600 -and $policy.platformWaitCapSeconds -eq 3600) 'Wait policy defaults changed'; Require ($policy.polling -eq 'disabled-for-blocking-runs') 'Polling policy changed'
$request=Join-Path ([IO.Path]::GetTempPath()) "v4-kernel-$([Guid]::NewGuid().ToString('N')).json"; [IO.File]::WriteAllText($request,'{"schemaVersion":1,"kind":"kernel-request","role":"implementer","workerId":"worker-1","constraintsOverlay":true,"contextSources":["README.md"],"budgets":{"contextTokens":512,"outputTokens":128}}'); $out=& (Join-Path $root 'bin/agentic-kernel.ps1') -RequestPath $request|ConvertFrom-Json; Require ($out.root -eq 'host-selected' -and $out.status -eq 'READY') 'Kernel root contract failed'
$replacement=Join-Path ([IO.Path]::GetTempPath()) "v4-replacement-$([Guid]::NewGuid().ToString('N')).json"; [IO.File]::WriteAllText($replacement,'{"schemaVersion":1,"kind":"kernel-request","role":"implementer","failure":{"workerId":"worker-1","reason":"usage-limit"},"contextSources":["README.md"],"budgets":{"contextTokens":512,"outputTokens":128}}'); $r=& (Join-Path $root 'bin/agentic-kernel.ps1') -RequestPath $replacement|ConvertFrom-Json; Require ($r.status -eq 'REPLACEMENT_REQUIRED' -and $r.replacement.workerId -eq 'worker-1-replacement') 'Replacement contract failed'; Require ($runtime -notmatch 'root.*becomes.*implementer') 'Root takeover policy is unsafe'
$executeRoot=Join-Path ([IO.Path]::GetTempPath()) "v4-execute-$([Guid]::NewGuid().ToString('N'))"; New-Item -ItemType Directory $executeRoot|Out-Null; [IO.File]::WriteAllText((Join-Path $executeRoot 'source.md'),'constraints'); $o=& (Join-Path $root 'bin/agentic-execute.ps1') -ProjectRoot $executeRoot -SourcePath 'source.md' -RequiredGuarantees @('GREEN') -AsJson|ConvertFrom-Json; Require ($o.kind -eq 'constraints-overlay' -and $o.root -eq 'host-selected' -and $o.requiredGuarantees[0] -eq 'GREEN') 'Execute overlay failed'; ExpectFailure {& (Join-Path $root 'bin/agentic-execute.ps1') -ProjectRoot $executeRoot -SourcePath 'missing.md'} 'Missing execute source did not fail closed'; ExpectFailure {& (Join-Path $root 'bin/agentic-execute.ps1') -ProjectRoot $executeRoot -SourcePath '..\outside.md'} 'Escaping execute source did not fail closed'
$temp=Join-Path ([IO.Path]::GetTempPath()) "v4-install-$([Guid]::NewGuid().ToString('N'))"; $h=Join-Path $temp 'harness'; $c=Join-Path $temp 'codex'; $a=Join-Path $temp 'agents'; $cu=Join-Path $temp 'cursor'; $g=Join-Path $temp 'gemini'; $cl=Join-Path $temp 'claude'; New-Item -ItemType Directory $temp|Out-Null
try { & (Join-Path $root 'scripts/install.ps1') -HarnessHome $h -CodexHome $c -AgentsHome $a -CursorHome $cu -GeminiHome $g -ClaudeHome $cl | Out-Null; foreach($p in @((Join-Path $c 'AGENTS.md'),(Join-Path $c 'agents/scout.toml'),(Join-Path $a 'skills/sdd-workflow/SKILL.md'),(Join-Path $h 'config/wait-policy.json'))){Require (Test-Path $p) "Clean install missing $p"}; Require ((Get-FileHash (Join-Path $root 'skills/sdd-workflow/SKILL.md')).Hash -eq (Get-FileHash (Join-Path $a 'skills/sdd-workflow/SKILL.md')).Hash) 'Installed skill content mismatch'; $cfg=Join-Path $c 'config.toml'; $first=Get-Content -Raw $cfg; Require (([regex]::Matches($first,'(?m)^\[agents\]$')).Count -eq 1) 'Clean install agents section count'; & (Join-Path $root 'scripts/install.ps1') -HarnessHome $h -CodexHome $c -AgentsHome $a -CursorHome $cu -GeminiHome $g -ClaudeHome $cl | Out-Null; $second=Get-Content -Raw $cfg; Require (([regex]::Matches($second,'(?m)^\[agents\]$')).Count -eq 1) 'Install is not idempotent'; Require ($first -eq $second) 'Managed config changed on idempotent install'; [IO.File]::WriteAllText($cfg,"[foo]`nvalue=1`n`n[bar]`nvalue=2`n`n[agents]`nold=true`n"); & (Join-Path $root 'scripts/install.ps1') -HarnessHome $h -CodexHome $c -AgentsHome $a -CursorHome $cu -GeminiHome $g -ClaudeHome $cl | Out-Null; $merged=Get-Content -Raw $cfg; Require ($merged.Contains('[foo]') -and $merged.Contains('[bar]') -and -not $merged.Contains('old=true')) 'Existing config merge failed'; $skipBefore=Get-Content -Raw $cfg; & (Join-Path $root 'scripts/install.ps1') -HarnessHome $h -CodexHome $c -AgentsHome $a -CursorHome $cu -GeminiHome $g -ClaudeHome $cl -SkipConfig | Out-Null; Require ((Get-Content -Raw $cfg) -eq $skipBefore) 'SkipConfig modified config'; $what=Join-Path $temp 'whatif'; & (Join-Path $root 'scripts/install.ps1') -HarnessHome $what -CodexHome (Join-Path $temp 'wc') -AgentsHome (Join-Path $temp 'wa') -CursorHome (Join-Path $temp 'wcu') -GeminiHome (Join-Path $temp 'wg') -ClaudeHome (Join-Path $temp 'wcl') -WhatIf | Out-Null; Require (-not (Test-Path $what)) 'WhatIf created files'; Require ((Get-Content -Raw (Join-Path $root 'scripts/install.ps1')) -notmatch '\.agentic-harness-v4') 'Legacy install path active' } finally { if(Test-Path $temp){Remove-Item -LiteralPath $temp -Recurse -Force} }
$runtimeRoot=Join-Path ([IO.Path]::GetTempPath()) "v4-runs-$([Guid]::NewGuid().ToString('N'))"; $pw=(Get-Command powershell.exe).Source; $ok=& (Join-Path $root 'bin/agentic-run.ps1') -FilePath $pw -ArgumentList @('-NoProfile','-Command','Start-Sleep -Milliseconds 1000; Write-Output smoke') -WorkingDirectory $root -RuntimeRoot $runtimeRoot -TimeoutSeconds 5 -RunId smoke 2>$null; $okObj=$ok|ConvertFrom-Json; Require ($okObj.status -eq 'COMPLETED') 'Runner completion status failed'; Require (Test-Path -LiteralPath $okObj.resultPath) 'Runner result file missing'; Require ($okObj.stdoutLog.StartsWith([IO.Path]::GetFullPath($runtimeRoot),[StringComparison]::OrdinalIgnoreCase)) 'Runner logs are not external'; & (Join-Path $root 'bin/agentic-run.ps1') -FilePath $pw -ArgumentList @('-NoProfile','-Command','Start-Sleep -Seconds 3') -WorkingDirectory $root -RuntimeRoot $runtimeRoot -TimeoutSeconds 1 -RunId timeout 2>$null; Require ($LASTEXITCODE -eq 124) 'Runner timeout smoke failed'
Write-Host 'V4 final refinement tests passed.'
