[CmdletBinding(SupportsShouldProcess=$true)] param([string]$HarnessHome=(Join-Path ([Environment]::GetFolderPath('UserProfile')) '.agentic-harness'),[string]$CodexHome=(Join-Path ([Environment]::GetFolderPath('UserProfile')) '.codex'),[string]$AgentsHome=(Join-Path ([Environment]::GetFolderPath('UserProfile')) '.agents'),[string]$CursorHome=(Join-Path ([Environment]::GetFolderPath('UserProfile')) '.cursor'),[string]$GeminiHome=(Join-Path ([Environment]::GetFolderPath('UserProfile')) '.gemini'),[string]$ClaudeHome=(Join-Path ([Environment]::GetFolderPath('UserProfile')) '.claude'),[switch]$SkipConfig)
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; $root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')); $m=Get-Content -Raw (Join-Path $root 'portable-manifest.json')|ConvertFrom-Json
. (Join-Path $PSScriptRoot 'adapter-tools.ps1')
foreach($d in $m.harnessInstall.directories){$s=Join-Path $root $d;$t=Join-Path $HarnessHome $d;if(-not(Test-Path $s)){throw "Missing source: $d"};if($PSCmdlet.ShouldProcess($t,'Install V4 directory')){New-Item -ItemType Directory -Force (Split-Path $t)|Out-Null;Copy-Item $s $t -Recurse -Force}}
foreach($f in $m.harnessInstall.files){$s=Join-Path $root $f;$t=Join-Path $HarnessHome $f;if($PSCmdlet.ShouldProcess($t,'Install V4 file')){New-Item -ItemType Directory -Force (Split-Path $t)|Out-Null;Copy-Item $s $t -Force}}
function Assert-ManagedPath([string]$Path,[string]$Base){$p=[IO.Path]::GetFullPath($Path);$b=[IO.Path]::GetFullPath($Base).TrimEnd('\');if(-not $p.StartsWith($b+'\',[StringComparison]::OrdinalIgnoreCase)){throw "Refusing path outside ${b}: $p"}}
function Install-ManagedContent([string]$Content,[string]$Target,[string]$Base,[string]$Relative){Assert-ManagedPath $Target $Base;$backup=Join-Path $Base (Join-Path 'portable-backups' (Get-Date -Format 'yyyyMMdd-HHmmss'));if((Test-Path $Target -PathType Leaf) -and $PSCmdlet.ShouldProcess($Target,"Back up to $backup\$Relative")){New-Item -ItemType Directory -Force (Split-Path (Join-Path $backup $Relative))|Out-Null;Copy-Item $Target (Join-Path $backup $Relative) -Force};if($PSCmdlet.ShouldProcess($Target,'Install managed instructions')){New-Item -ItemType Directory -Force (Split-Path $Target)|Out-Null;[IO.File]::WriteAllText($Target,$Content,[Text.UTF8Encoding]::new($false))}}
function Install-ManagedDirectory([string]$Source,[string]$Target,[string]$Base,[string]$Relative){Assert-ManagedPath $Target $Base;if($PSCmdlet.ShouldProcess($Target,'Install managed V4 directory')){$backup=Join-Path $Base (Join-Path 'portable-backups' (Get-Date -Format 'yyyyMMdd-HHmmss'));if(Test-Path $Target -PathType Container){New-Item -ItemType Directory -Force (Join-Path $backup (Split-Path $Relative -Parent))|Out-Null;Copy-Item $Target (Join-Path $backup $Relative) -Recurse -Force;Remove-Item -LiteralPath $Target -Recurse -Force};New-Item -ItemType Directory -Force $Target|Out-Null;Copy-Item (Join-Path $Source '*') $Target -Recurse -Force}}
$codexA=Get-AdapterManifest $root 'Codex';Install-ManagedContent (Get-AdapterInstructionContent $root $codexA) (Join-Path $CodexHome 'AGENTS.md') $CodexHome 'AGENTS.md'
$cursorA=Get-AdapterManifest $root 'Cursor';Install-ManagedContent (Get-AdapterInstructionContent $root $cursorA) (Join-Path $CursorHome 'rules\agentic-harness.mdc') $CursorHome 'rules\agentic-harness.mdc'
$cursorAgents=Join-Path $CursorHome 'agents';foreach($role in $m.agentFiles){$raw=Get-Content -Raw (Join-Path $root "global\agents\$role");$name=[regex]::Match($raw,'(?m)^name\s*=\s*"([^"]+)"').Groups[1].Value;$desc=[regex]::Match($raw,'(?m)^description\s*=\s*"([^"]+)"').Groups[1].Value;$body=[regex]::Match($raw,'(?s)developer_instructions\s*=\s*"""\s*(.*?)\s*"""').Groups[1].Value.Trim();if(-not $name){throw "Cannot project role $role"};Install-ManagedContent "---`nname: $name`ndescription: $desc`n---`n`n$body`n" (Join-Path $cursorAgents "$name.md") $CursorHome "agents\$name.md"}
$gemA=Get-AdapterManifest $root 'Antigravity';Install-ManagedContent (Get-AdapterInstructionContent $root $gemA) (Join-Path $GeminiHome 'GEMINI.md') $GeminiHome 'GEMINI.md'
$claudeA=Get-AdapterManifest $root 'Claude';Install-ManagedContent (Get-AdapterInstructionContent $root $claudeA) (Join-Path $ClaudeHome 'CLAUDE.md') $ClaudeHome 'CLAUDE.md'
foreach($skill in $m.skills){Install-ManagedDirectory (Join-Path $root "skills\$skill") (Join-Path $AgentsHome "skills\$skill") $AgentsHome "skills\$skill";Install-ManagedDirectory (Join-Path $root "skills\$skill") (Join-Path $GeminiHome "config\skills\$skill") $GeminiHome "config\skills\$skill";Install-ManagedDirectory (Join-Path $root "skills\$skill") (Join-Path $ClaudeHome "skills\$skill") $ClaudeHome "skills\$skill"}
Install-ManagedContent (Get-Content -Raw (Join-Path $root 'config\skill-index.md')) (Join-Path $AgentsHome 'skill-index.md') $AgentsHome 'skill-index.md'
foreach($role in $m.agentFiles){$src=Join-Path $root "global\agents\$role";Install-ManagedContent (Get-Content -Raw $src) (Join-Path $CodexHome "agents\$role") $CodexHome "agents\$role"}
if(-not $SkipConfig){
    $configPath=Join-Path $CodexHome 'config.toml'; $fragment=Get-Content -Raw (Join-Path $root 'config\agents.toml')
    if($PSCmdlet.ShouldProcess($configPath,'Merge managed [agents] configuration')){
        New-Item -ItemType Directory -Force (Split-Path $configPath)|Out-Null
        if(Test-Path -LiteralPath $configPath -PathType Leaf){$backup=Join-Path $CodexHome (Join-Path 'portable-backups' (Get-Date -Format 'yyyyMMdd-HHmmss'));New-Item -ItemType Directory -Force $backup|Out-Null;Copy-Item $configPath (Join-Path $backup 'config.toml') -Force;$existing=Get-Content -Raw $configPath}else{$existing=''}
        $without=[regex]::Replace($existing,'(?ms)^\[agents\]\s*.*?(?=^\[|\z)','')
        [IO.File]::WriteAllText($configPath,($without.TrimEnd()+"`n`n"+$fragment.Trim()+"`n"),[Text.UTF8Encoding]::new($false))
    }
}
Write-Host "V4 harness installed at $HarnessHome; Codex=$CodexHome; Cursor=$CursorHome; Antigravity=$GeminiHome; Claude=$ClaudeHome"
