[CmdletBinding()] param()
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; $root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$m=Get-Content -Raw (Join-Path $root 'portable-manifest.json')|ConvertFrom-Json; if($m.schemaVersion -ne 5){throw 'Unsupported manifest schema'}
foreach($p in @('README.md','global/AGENTS.md','profiles/coder/PROFILE.md','config/skill-index.md','config/agents.toml','config/wait-policy.json','bin/agentic-run.ps1','bin/agentic-finalize.ps1','bin/agentic-kernel.ps1','bin/agentic-execute.ps1')){if(-not(Test-Path (Join-Path $root $p))){throw "Missing required path: $p"}}
$w=Get-Content -Raw (Join-Path $root 'config/wait-policy.json')|ConvertFrom-Json; if($w.schemaVersion -ne 1 -or $w.defaultCommandTimeoutSeconds -ne 3600 -or $w.defaultAgentWaitSeconds -ne 3600 -or $w.platformWaitCapSeconds -ne 3600 -or $w.polling -ne 'disabled-for-blocking-runs'){throw 'Invalid wait policy'}
if((Get-Content -Raw (Join-Path $root 'scripts/install.ps1')) -match '\.agentic-harness-v4'){throw 'Legacy installation path remains active'}
. (Join-Path $root 'scripts/adapter-tools.ps1'); foreach($a in $m.adapters){$x=Get-AdapterManifest $root $a; if($x.installMode -ne 'always'){throw "Adapter $a not always installed"}; foreach($s in $x.instructionSources){if(-not(Test-Path (Join-Path $root $s))){throw "Missing source: $s"}}; $out=Join-Path $root $x.instructionOutput; if(-not(Test-Path $out)){throw "Missing output: $a"}; $actual=((Get-Content -Raw $out)-replace "`r`n","`n").Trim(); $expected=((Get-AdapterInstructionContent $root $x)-replace "`r`n","`n").Trim(); if($actual -ne $expected){throw "Stale output: $a"}}
$expectedSkills=@('sdd-workflow','systematic-debugging','repo-aware-architecture','revise-and-deploy'); if(@($m.skills).Count -ne $expectedSkills.Count -or @($m.skills|Where-Object{$_ -notin $expectedSkills}).Count -ne 0 -or @($expectedSkills|Where-Object{$_ -notin $m.skills}).Count -ne 0){throw 'Skill allowlist mismatch'}; foreach($s in $m.skills){if(-not(Test-Path (Join-Path $root "skills/$s/SKILL.md"))){throw "Missing skill: $s"}}
foreach($s in $m.skills){foreach($md in Get-ChildItem (Join-Path $root "skills/$s") -Recurse -Filter '*.md'){foreach($match in [regex]::Matches((Get-Content -Raw $md.FullName),'\[[^\]]+\]\(([^)#]+)')){$link=$match.Groups[1].Value;if($link -notmatch '^(https?|mailto):' -and -not(Test-Path (Join-Path $md.DirectoryName $link))){throw "Dead Markdown reference: $link"}}}}
# Retired runtime names are forbidden in executable/config surfaces. Historical
# prose is allowed to explain the migration without activating dead code.
$activeRoots=@('bin','scripts','core','config','global','adapters','profiles','skills')
foreach($base in $activeRoots){$basePath=Join-Path $root $base;if(Test-Path $basePath){foreach($f in Get-ChildItem $basePath -Recurse -File | Where-Object {$_.Extension -in @('.ps1','.psm1','.json','.toml','.py','.pyproject')}){if($f.FullName -match '(?i)langgraph|workflow-compile|workflow-validate|workflow-resolve|workflow-receipts|pyproject'){throw "Legacy active artifact: $($f.FullName)"}}}}
if(Test-Path (Join-Path $root 'skills/sdd-workflow/references/model-routing.md')){throw 'Legacy model-routing reference remains'}
Write-Host "V4 verification passed: $((Get-ChildItem $root -Recurse -File).Count) files"
