[CmdletBinding()] param()
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; $root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$m=Get-Content -Raw (Join-Path $root 'portable-manifest.json')|ConvertFrom-Json; if($m.schemaVersion -ne 5){throw 'Unsupported manifest schema'}
foreach($p in @('README.md','global/AGENTS.md','profiles/coder/PROFILE.md','config/agents.toml','config/wait-policy.json','bin/agentic-run.ps1','bin/agentic-finalize.ps1','bin/agentic-kernel.ps1','bin/agentic-execute.ps1')){if(-not(Test-Path (Join-Path $root $p))){throw "Missing required path: $p"}}
$w=Get-Content -Raw (Join-Path $root 'config/wait-policy.json')|ConvertFrom-Json; if($w.schemaVersion -ne 1 -or $w.defaultCommandTimeoutSeconds -ne 3600 -or $w.defaultAgentWaitSeconds -ne 3600 -or $w.platformWaitCapSeconds -ne 3600 -or $w.polling -ne 'disabled-for-blocking-runs'){throw 'Invalid wait policy'}
if((Get-Content -Raw (Join-Path $root 'scripts/install.ps1')) -match '\.agentic-harness-v4'){throw 'Legacy installation path remains active'}
. (Join-Path $root 'scripts/adapter-tools.ps1'); foreach($a in $m.adapters){$x=Get-AdapterManifest $root $a; if($x.installMode -ne 'always'){throw "Adapter $a not always installed"}; foreach($s in $x.instructionSources){if(-not(Test-Path (Join-Path $root $s))){throw "Missing source: $s"}}; $out=Join-Path $root $x.instructionOutput; if(-not(Test-Path $out)){throw "Missing output: $a"}; $actual=((Get-Content -Raw $out)-replace "`r`n","`n").Trim(); $expected=((Get-AdapterInstructionContent $root $x)-replace "`r`n","`n").Trim(); if($actual -ne $expected){throw "Stale output: $a"}}
$expectedSkills=@('sdd-workflow','systematic-debugging','repo-aware-architecture'); if(@($m.skills).Count -ne 3 -or @($m.skills|Where-Object{$_ -notin $expectedSkills}).Count -ne 0){throw 'Skill allowlist mismatch'}; foreach($s in $m.skills){if(-not(Test-Path (Join-Path $root "skills/$s/SKILL.md"))){throw "Missing skill: $s"}}
foreach($s in $m.skills){foreach($md in Get-ChildItem (Join-Path $root "skills/$s") -Recurse -Filter '*.md'){foreach($match in [regex]::Matches((Get-Content -Raw $md.FullName),'\[[^\]]+\]\(([^)#]+)')){$link=$match.Groups[1].Value;if($link -notmatch '^(https?|mailto):' -and -not(Test-Path (Join-Path $md.DirectoryName $link))){throw "Dead Markdown reference: $link"}}}}
foreach($f in Get-ChildItem $root -Recurse -File){if($f.FullName -match '(?i)workflow-receipts|langgraph|pyproject'){throw "Legacy artifact: $($f.FullName)"}}
Write-Host "V4 verification passed: $((Get-ChildItem $root -Recurse -File).Count) files"
