[CmdletBinding()] param()
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; $root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')); $m=Get-Content -Raw (Join-Path $root 'portable-manifest.json')|ConvertFrom-Json; if($m.schemaVersion -ne 5){throw 'Unsupported manifest schema'}
foreach($p in @('README.md','global/AGENTS.md','profiles/coder/PROFILE.md','profiles/assistant/PROFILE.md','profiles/knowledge/PROFILE.md','profiles/home/PROFILE.md','config/agents.toml','bin/agentic-run.ps1','bin/agentic-finalize.ps1','bin/agentic-kernel.ps1','bin/agentic-execute.ps1')){if(-not(Test-Path (Join-Path $root $p))){throw "Missing required path: $p"}}
foreach($a in $m.adapters){$x=Get-Content -Raw (Join-Path $root "adapters/$a/adapter.json")|ConvertFrom-Json;if($x.installMode -ne 'always'){throw "Adapter $a not always installed"};foreach($s in $x.instructionSources){if(-not(Test-Path (Join-Path $root $s))){throw "Missing source: $s"}}; $out=Join-Path $root $x.instructionOutput;if(-not(Test-Path $out)){throw "Missing materialized output: $($x.instructionOutput)"}; . (Join-Path $root 'scripts/adapter-tools.ps1'); if((Get-Content -Raw $out) -ne (Get-AdapterInstructionContent $root $x)){throw "Stale output: $a"}}
if (@($m.adapters) -notcontains 'claude'){throw 'Claude adapter missing from manifest'}
$expectedSkills=@('sdd-workflow','systematic-debugging','repo-aware-architecture'); if(@($m.skills).Count -ne $expectedSkills.Count -or @(@($m.skills) | Where-Object {$_ -notin $expectedSkills}).Count -ne 0 -or @($expectedSkills | Where-Object {$_ -notin @($m.skills)}).Count -ne 0){throw 'Manifest skill allowlist mismatch'}; foreach($s in $m.skills){if(-not(Test-Path (Join-Path $root "skills/$s/SKILL.md"))){throw "Missing skill: $s"}}
$skillDirs=@(Get-ChildItem (Join-Path $root 'skills') -Directory | Select-Object -ExpandProperty Name); if(@($skillDirs | Where-Object {$_ -notin $expectedSkills}).Count -ne 0){throw 'Unexpected skill directory'}
$forbidden='(?i)(auth\.json|sessions|cache|attachments|browser-state|\.sqlite|\.jsonl|\.gguf|safetensors|portable-backups)'; foreach($f in Get-ChildItem $root -Recurse -File){$r=$f.FullName.Substring($root.Length);if($r -match $forbidden){throw "Forbidden artifact: $r"};if($f.Extension -eq '.json'){Get-Content -Raw $f|ConvertFrom-Json|Out-Null}}
Write-Host "V4 verification passed: $((Get-ChildItem $root -Recurse -File).Count) files"
